### ISSUE TITLE
Presentation -  Implement CEO's Feedback

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/c11-apollo-bandcamp-tracker#111]
We have received some general feedback from our CEO (in Slack) that we need to apply to our presentation

### Tasks

- [ ] Read and understand feedback, ask questions if needed
- [ ] Improve presentation and slides

**Comment by alina-101** [comment]
Added CI/CD through showing github actions. 
Removed role names
Added a Key technologies slide
