### ISSUE TITLE
Dashboard - Dockerise

### ISSUE THREAD

**Issue by alina-101** [Zhi-704/c11-apollo-bandcamp-tracker#97]
- [x] create `Dockerfile`
- [x] expose port
- [x] create image
- [x] run image locally
- [x] create ECR
- [ ] push image to ECR

As an engineer I need to dockerise my dashboard so that I am able to deploy it to AWS so that it is always running and available.

**Comment by e-lemma** [comment]
Everything is complete, but an issue with some queries needs to be addressed before the containerised dashboard can be properly tested and deployed on the cloud.

**Comment by e-lemma** [comment]
It can still be added to the repository as the dockerfile code is the same regardless.
